# Generated by Django 4.0 on 2021-12-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vets')),
                ('experience', models.IntegerField(default=0)),
                ('contacts', models.CharField(max_length=255)),
            ],
        ),
    ]
